- hosts: juliet
  vars:
    speech: |
      The clock struck nine when I did send the nurse;
      In half an hour she promised to return.
      Perchance she cannot meet him: that's not so.
      O, she is lame! love's heralds should be thoughts,
      Which ten times faster glide than the sun's beams,
      Driving back shadows over louring hills:
      Therefore do nimble-pinion'd doves draw love,
      And therefore hath the wind-swift Cupid wings.
      Now is the sun upon the highmost hill
      Of this day's journey, and from nine till twelve
      Is three long hours, yet she is not come.
      Had she affections and warm youthful blood,
      She would be as swift in motion as a ball;
      My words would bandy her to my sweet love,
      And his to me:
      But old folks, many feign as they were dead;
      Unwieldy, slow, heavy and pale as lead.
      O God, she comes!
      O honey nurse, what news?
      Hast thou met with him? Send thy man away.
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: nurse
  vars:
    speech: |
      Peter, stay at the gate.
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: juliet
  vars:
    speech: |
      Now, good sweet nurse,--O Lord, why look'st thou sad?
      Though news be sad, yet tell them merrily;
      If good, thou shamest the music of sweet news
      By playing it to me with so sour a face.
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: nurse
  vars:
    speech: |
      I am a-weary, give me leave awhile:
      Fie, how my bones ache! what a jaunt have I had!
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: juliet
  vars:
    speech: |
      I would thou hadst my bones, and I thy news:
      Nay, come, I pray thee, speak; good, good nurse, speak.
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: nurse
  vars:
    speech: |
      Jesu, what haste? can you not stay awhile?
      Do you not see that I am out of breath?
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: juliet
  vars:
    speech: |
      How art thou out of breath, when thou hast breath
      To say to me that thou art out of breath?
      The excuse that thou dost make in this delay
      Is longer than the tale thou dost excuse.
      Is thy news good, or bad? answer to that;
      Say either, and I'll stay the circumstance:
      Let me be satisfied, is't good or bad?
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: nurse
  vars:
    speech: |
      Well, you have made a simple choice; you know not
      how to choose a man: Romeo! no, not he; though his
      face be better than any man's, yet his leg excels
      all men's; and for a hand, and a foot, and a body,
      though they be not to be talked on, yet they are
      past compare: he is not the flower of courtesy,
      but, I'll warrant him, as gentle as a lamb. Go thy
      ways, wench; serve God. What, have you dined at home?
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: juliet
  vars:
    speech: |
      No, no: but all this did I know before.
      What says he of our marriage? what of that?
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: nurse
  vars:
    speech: |
      Lord, how my head aches! what a head have I!
      It beats as it would fall in twenty pieces.
      My back o' t' other side,--O, my back, my back!
      Beshrew your heart for sending me about,
      To catch my death with jaunting up and down!
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: juliet
  vars:
    speech: |
      I' faith, I am sorry that thou art not well.
      Sweet, sweet, sweet nurse, tell me, what says my love?
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: nurse
  vars:
    speech: |
      Your love says, like an honest gentleman, and a
      courteous, and a kind, and a handsome, and, I
      warrant, a virtuous,--Where is your mother?
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: juliet
  vars:
    speech: |
      Where is my mother! why, she is within;
      Where should she be? How oddly thou repliest!
      'Your love says, like an honest gentleman,
      Where is your mother?'
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: nurse
  vars:
    speech: |
      O God's lady dear!
      Are you so hot? marry, come up, I trow;
      Is this the poultice for my aching bones?
      Henceforward do your messages yourself.
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: juliet
  vars:
    speech: |
      Here's such a coil! come, what says Romeo?
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: nurse
  vars:
    speech: |
      Have you got leave to go to shrift to-day?
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: juliet
  vars:
    speech: |
      I have.
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: nurse
  vars:
    speech: |
      Then hie you hence to Friar Laurence' cell;
      There stays a husband to make you a wife:
      Now comes the wanton blood up in your cheeks,
      They'll be in scarlet straight at any news.
      Hie you to church; I must another way,
      To fetch a ladder, by the which your love
      Must climb a bird's nest soon when it is dark:
      I am the drudge and toil in your delight,
      But you shall bear the burden soon at night.
      Go; I'll to dinner: hie you to the cell.
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: juliet
  vars:
    speech: |
      Hie to high fortune! Honest nurse, farewell.
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

