- hosts: lady_capulet
  vars:
    speech: |
      Hold, take these keys, and fetch more spices, nurse.
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: nurse
  vars:
    speech: |
      They call for dates and quinces in the pastry.
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: capulet
  vars:
    speech: |
      Come, stir, stir, stir! the second cock hath crow'd,
      The curfew-bell hath rung, 'tis three o'clock:
      Look to the baked meats, good Angelica:
      Spare not for the cost.
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: nurse
  vars:
    speech: |
      Go, you cot-quean, go,
      Get you to bed; faith, You'll be sick to-morrow
      For this night's watching.
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: capulet
  vars:
    speech: |
      No, not a whit: what! I have watch'd ere now
      All night for lesser cause, and ne'er been sick.
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: lady_capulet
  vars:
    speech: |
      Ay, you have been a mouse-hunt in your time;
      But I will watch you from such watching now.
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: capulet
  vars:
    speech: |
      A jealous hood, a jealous hood!
      Now, fellow,
      What's there?
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: first_servant
  vars:
    speech: |
      Things for the cook, sir; but I know not what.
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: capulet
  vars:
    speech: |
      Make haste, make haste.
      Sirrah, fetch drier logs:
      Call Peter, he will show thee where they are.
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: second_servant
  vars:
    speech: |
      I have a head, sir, that will find out logs,
      And never trouble Peter for the matter.
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: capulet
  vars:
    speech: |
      Mass, and well said; a merry whoreson, ha!
      Thou shalt be logger-head. Good faith, 'tis day:
      The county will be here with music straight,
      For so he said he would: I hear him near.
      Nurse! Wife! What, ho! What, nurse, I say!
      Go waken Juliet, go and trim her up;
      I'll go and chat with Paris: hie, make haste,
      Make haste; the bridegroom he is come already:
      Make haste, I say.
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

